(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Capfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Vagrantfile$" . ruby-mode))

(defun rae-ruby-mode-defaults ()
  (inf-ruby-minor-mode +1)
  (ruby-tools-mode +1)
  (flymake-ruby-load)
  (flymake-cursor-mode)
  (ruby-end-mode))
(add-hook 'ruby-mode-hook 'rae-ruby-mode-defaults)

(global-rbenv-mode)
